version: "3"
volumes:
  node_modules:
  build:
services:
  mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
      - ./db/:/data/db/
  # redis:
  #   image: redis:6.0.8-alpine
  #   restart: always
  web:
    build: .
    restart: always
    environment:
      - HTTP_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      # - redis
